### ISSUE TITLE
Using api created key results in error decrypting JWE from from x-ebay-signature-key header

### ISSUE THREAD

**Issue by martin3mf** [eBay/digital-signature-verification-ebay-api#10]
Testing with the test keys works fine, but as soon as i use the given keys from the api call i get an error:

```
curl --location --request POST 'http://localhost:8080/verifysignature' --header 'Content-Type: application/json'\
 --header 'Signature-Input: sig1=("content-digest" "x-ebay-signature-key" "@method" "@path" "@authority");created=1668361090'\
 --header 'Content-Digest: sha-256=:X48E9qOokqqrvdts8nOJRJN3OWDUoyWxBf7kbu9DBPE=:'\
 --header 'Signature: sig1=:P07yEAh3b3vMC1BZm3dDcn8uljEkMzoDSJwnd7PnH3jLBdbtRd6IiFD79RTmZPHaOt4Sqs5MGVr1+v+ORHHHAg==:'\
 --header 'x-ebay-signature-key: eyJ6aXAiOiJERUYiLCJraWQiOiJiNmI4ZWY2MC0zODU4LTRiMGUtYTI5My1mZjQyOGJkZmMyZmMiLCJlbmMiOiJBMjU2R0NNIiwidGFnIjoieXVoRjlxZzU5LUZGUDlCRTBISmw4QSIsImFsZyI6IkEyNTZHQ01LVyIsIml2IjoiaXY0OVVPNU4xSHAzTU9jRyJ9.lPTcvHd6RiNg-tu8C8VC9E6vIVEZtDKW8N1VEwBJo1U.2rjnfN_wvrFnVIUx.9eRiJRyoOxh6uFxYGiwGZcduXCsDcusUm8aqFJjS6isLUDa6tWqhhBF-GojROSABgnhaUKcVWY6zlDcDssATzc_pI44SPL_JUFIXYPYvM0Mh09LvidHGCAGF4b3vPEgLfOjpzX0WbriXHk6on3z-04OaNl1INed7HdtMExlwXCWp6sLZNnikBEfiQYQvo6fZWpE4H6_OV_zDNUN0axjzfIu3l_yvkIMhE_pPtOyRnAIGKjBHSK6o5dJuJNGyYnrBZcDgQvg.oa8upm0o2IsJFDs29UqLAg' --data-raw '{"hello": "world"}'
```

Results in:

```
2022-11-13 17:27:06.705  INFO 11 --- [nio-8080-exec-2] c.e.s.VerificationService                : Calculated base:
"content-digest": sha-256=:X48E9qOokqqrvdts8nOJRJN3OWDUoyWxBf7kbu9DBPE=:
"x-ebay-signature-key": eyJ6aXAiOiJERUYiLCJlbmMiOiJBMjU2R0NNIiwidGFnIjoiSXh2dVRMb0FLS0hlS0Zoa3BxQ05CUSIsImFsZyI6IkEyNTZHQ01LVyIsIml2IjoiaFd3YjNoczk2QzEyOTNucCJ9.2o02pR9SoTF4g_5qRXZm6tF4H52TarilIAKxoVUqjd8.3qaF0KJN-rFHHm_P.AMUAe9PPduew09mANIZ-O_68CCuv6EIx096rm9WyLZnYz5N1WFDQ3jP0RBkbaOtQZHImMSPXIHVaB96RWshLuJsUgCKmTAwkPVCZv3zhLxZVxMXtPUuJ-ppVmPIv0NzznWCOU5Kvb9Xux7ZtnlvLXgwOFEix-BaWNomUAazbsrUCbrp514GIea3butbyxXLNi6R9TJUNh8V2uan-optT1MMyS7eMQnVGL5rYBULk.9K5ucUqAu0DqkkhgubsHHw
"@method": POST
"@path": /verifysignature
"@authority": localhost:8080
"@signature-params": ("content-digest" "x-ebay-signature-key" "@method" "@path" "@authority");created=1658440308
2022-11-13 17:27:06.812  INFO 11 --- [nio-8080-exec-2] c.e.s.VerificationService                : Message signature verified
2022-11-13 17:38:44.127  INFO 11 --- [nio-8080-exec-3] c.e.s.VerificationService                : Calculated base:
"content-digest": sha-256=:X48E9qOokqqrvdts8nOJRJN3OWDUoyWxBf7kbu9DBPE=:
"x-ebay-signature-key": eyJ6aXAiOiJERUYiLCJraWQiOiJiNmI4ZWY2MC0zODU4LTRiMGUtYTI5My1mZjQyOGJkZmMyZmMiLCJlbmMiOiJBMjU2R0NNIiwidGFnIjoieXVoRjlxZzU5LUZGUDlCRTBISmw4QSIsImFsZyI6IkEyNTZHQ01LVyIsIml2IjoiaXY0OVVPNU4xSHAzTU9jRyJ9.lPTcvHd6RiNg-tu8C8VC9E6vIVEZtDKW8N1VEwBJo1U.2rjnfN_wvrFnVIUx.9eRiJRyoOxh6uFxYGiwGZcduXCsDcusUm8aqFJjS6isLUDa6tWqhhBF-GojROSABgnhaUKcVWY6zlDcDssATzc_pI44SPL_JUFIXYPYvM0Mh09LvidHGCAGF4b3vPEgLfOjpzX0WbriXHk6on3z-04OaNl1INed7HdtMExlwXCWp6sLZNnikBEfiQYQvo6fZWpE4H6_OV_zDNUN0axjzfIu3l_yvkIMhE_pPtOyRnAIGKjBHSK6o5dJuJNGyYnrBZcDgQvg.oa8upm0o2IsJFDs29UqLAg
"@method": POST
"@path": /verifysignature
"@authority": localhost:8080
"@signature-params": ("content-digest" "x-ebay-signature-key" "@method" "@path" "@authority");created=1668361090
com.ebay.signaturevalidation.SignatureException: Error decrypting the JWE from x-ebay-signature-key header
	at com.ebay.signaturevalidation.KeypairService.decryptJWE(KeypairService.java:62)
	at com.ebay.signaturevalidation.VerificationService.verifyJWT(VerificationService.java:66)
	at com.ebay.signaturevalidation.VerificationService.verifyMessage(VerificationService.java:52)
	at com.ebay.signaturevalidation.VerificationInterceptor.preHandle(VerificationInterceptor.java:31)
	at org.springframework.web.servlet.HandlerExecutionChain.applyPreHandle(HandlerExecutionChain.java:148)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1062)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:681)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1787)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.nimbusds.jose.JOSEException: AES/GCM/NoPadding decryption failed: Tag mismatch!
	at com.nimbusds.jose.crypto.impl.AESGCM.decrypt(AESGCM.java:301)
	at com.nimbusds.jose.crypto.impl.AESGCMKW.decryptCEK(AESGCMKW.java:97)
	at com.nimbusds.jose.crypto.AESDecrypter.decrypt(AESDecrypter.java:222)
	at com.nimbusds.jose.JWEObject.decrypt(JWEObject.java:420)
	at com.ebay.signaturevalidation.KeypairService.decryptJWE(KeypairService.java:59)
	... 44 more
Caused by: javax.crypto.AEADBadTagException: Tag mismatch!
	at java.base/com.sun.crypto.provider.GaloisCounterMode.decryptFinal(GaloisCounterMode.java:623)
	at java.base/com.sun.crypto.provider.CipherCore.finalNoPadding(CipherCore.java:1116)
	at java.base/com.sun.crypto.provider.CipherCore.fillOutputBuffer(CipherCore.java:1053)
	at java.base/com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:853)
	at java.base/com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:446)
	at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2202)
	at com.nimbusds.jose.crypto.impl.AESGCM.decrypt(AESGCM.java:297)
	... 48 more
```

**Comment by Xaohs** [comment]
I am running into the same problem. 

Validating against the test keys provided in this repo works as expected, but as soon as I try using the key's returned by eBay's key API it has an error decrypting the JWE key provided. 

Calling against `http://localhost:8080/verifysignature`, same error as OP. 
I've also tested calling against the actual eBay API, which nets in the same error  `Error decrypting the JWE from x-ebay-signature-key header`.

**Comment by uherberg** [comment]
@martin3mf @Xaohs This is intended. The keys from the key management API can't be used with this container. The reason is that we have to use a different masterkey used to encrypt the JWE in the container from the masterkey used on the eBay developer APIs. The masterkey used in this container could otherwise be used to create valid JWEs on the ebay developer APIs. 

I will add a note in the README and also in the response from the docker container to make clear that these keys are not interchangable.

**Comment by uherberg** [comment]
I made this clearer in this PR: https://github.com/eBay/digital-signature-verification-ebay-api/pull/14
